// Generated by CoffeeScript 1.8.0
window.id = function(id) {
  return document.getElementById(id);
};

window.select = function(selector) {
  return document.querySelectorAll(selector);
};

window.find_parent = function(tagName, search) {
  if (search.tagName.toLowerCase() === tagName) {
    return search;
  } else if (search === document.body) {
    return null;
  } else if (search.parentElement) {
    return find_parent(tagName, search.parentElement);
  }
};

//# sourceMappingURL=common.js.map
